# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1bafbfefc141db29022d33559c53528feea99f41dfd62bae0d64784f5153d55d6b66a298b17cf96138a6dfe1df14b33a0763120916c0eb7e571ec871915064a

test:
  secret_key_base: ea025e115bbc1e1eb75d3e017a092a522ed29329b8a856b1073c3341379070a20cb42c60f959d0ce0bed498d601e0bb8d0a3c5e63858075cde53e563bb8d87ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
